# Generated by Django 5.0 on 2024-01-04 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('level', models.CharField(choices=[('0', 'Factory'), ('1', 'Retail'), ('2', 'IP')], default='2', max_length=7, verbose_name='Уровень')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Задолженность')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Почта')),
                ('country', models.CharField(max_length=64, verbose_name='Страна')),
                ('city', models.CharField(max_length=64, verbose_name='Город')),
                ('street', models.CharField(max_length=64, verbose_name='Улица')),
                ('number_house', models.IntegerField(verbose_name='Номер дома')),
                ('products', models.CharField(max_length=64, verbose_name='Продукт')),
                ('model', models.CharField(max_length=64, verbose_name='Модель')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата выхода на рынок')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelsales.networkelement', verbose_name='Поставщик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сеть',
                'verbose_name_plural': 'Сети',
            },
        ),
    ]
